CREATE SEQUENCE BENEFICIO_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE BENEFICIO (ID BIGINT NOT NULL PRIMARY KEY, NOME VARCHAR(100) NOT NULL, DESCRICAO VARCHAR(255), VALOR DECIMAL(15, 2) NOT NULL, ATIVO BOOLEAN DEFAULT TRUE, VERSION BIGINT DEFAULT 0);
