INSERT INTO BENEFICIO (ID, NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES (NEXT VALUE FOR BENEFICIO_ID_SEQ, 'Beneficio A', 'Descrição A', 1000.00, TRUE, 0);
INSERT INTO BENEFICIO (ID, NOME, DESCRICAO, VALOR, ATIVO, VERSION) VALUES (NEXT VALUE FOR BENEFICIO_ID_SEQ, 'Beneficio B', 'Descrição B', 500.00, TRUE, 0);
